### ISSUE TITLE
[BUG]: Member Counter for Minecraft server is stuck at 16

### ISSUE THREAD

**Issue by Frodo-11** [eduardozgz/member-counter-bot#102]
**Describe the bug**
The game counter for "minecraft" is stuck at 16 when it updates. I have tried resetting it multiple times and every time it goes straight to 16

**To Reproduce**
1. Create the voice channel called "MC Server Counter"
2. Enter the counter protocol using {game:minecraft:74.91.125.84:25565} 
3. Wait for it update on its own
4. After it updates it goes right to 16

**Expected behavior**
I expected it to count the amount of players on our MC server just like it does for our FiveM and Ark servers.

**Screenshots**
https://imgur.com/U8hlGxp

**Additional context**
Got nothing to add here

**Comment by eduardozgz** [comment]
I couldn't reproduce this bug because your server is apparently offline, also, the count returned by this counter is returned by [node-gamedig](https://github.com/gamedig/node-gamedig#readme), so you should [open a issue there](https://github.com/gamedig/node-gamedig/issues/new) saying that the lib is not returning the correct amount for your server
